apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: financial-risk-dev

resources:
  - namespace.yaml
  - ../../base

images:
  - name: financial-risk-data-platform
    newName: 000000000000.dkr.ecr.us-east-1.amazonaws.com/financial-risk-data-platform
    newTag: bootstrap

patches:
  - path: service-account-patch.yaml
  - path: cronjob-patch.yaml
